runall: main.cpp
	g++ -o main.out -std=c++11 -O2 -Wall main.cpp
	echo "000,000,000 ABD,BAC,DCA ABD,BAC,DCA" | ./main.out
	echo "011,101,110 ABD,BAC,DCA ABD,BAC,DCA" | ./main.out
	echo "011000,101000,110000,000011,000101,000110 ABDFFF,BACFFF,DCAFFF,FFFABD,FFFBAC,FFFDCA ABDFFF,BACFFF,DCAFFF,FFFABD,FFFBAC,FFFDCA" | ./main.out
	echo "01,10 AB,BA AJ,JA" | ./main.out